# 使用 --spring.profiles.active=postgres 切换到PostgreSQL。
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/webdesign}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
